/**
 * @description Helps with drawing using the d attribute of a <path> element
 */
export default class PathD {
  data: string;

  constructor() {
    this.data = "";
  }

  /**
   * @description Move to the position (x, y)
   */
  public MoveTo(x: number, y: number) {
    this.data += `M${x},${y}`;
  }

  /**
   * @description Draw a line to the position (x, y)
   */
  public LineTo(x: number, y: number) {
    this.data += `L${x},${y}`;
  }

  /**
   * @description Move to (x, y) in an arc, the lengths of two axes of an
   *  ellipse of length rx (radii[0]) and ry (radii[1]) respectfully. The
   *  this ellipse can be rotated an amount. The large arc flags outputs the
   *  larger of two arcs generated by the ellipse and the sweep flag makes
   *  the arc drawn in a counter clockwise direction.
   *
   * @param x
   * @param y
   * @param radii
   * @param rotation
   * @param largeArc
   * @param sweep
   */
  public ArcTo(
    x: number,
    y: number,
    radii: [number, number],
    rotation: number,
    largeArc: boolean,
    sweep: boolean
  ) {
    const largeArcValue = largeArc ? 1 : 0;
    const sweepValue = sweep ? 1 : 0;

    this.data += `A${radii[0]},${radii[1]},${rotation},${largeArcValue},${sweepValue},${x},${y}`;
  }

  get d(): string {
    return this.data;
  }
}
